## phython libraries

## create 1D array

In [15]:
import numpy as np
x=np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
type(x)

numpy.ndarray

## create 2D array

In [8]:
y=np.array([[1,2,3],[3,4,5]])
print(y)

[[1 2 3]
 [3 4 5]]


## create 3D array

In [17]:
z=np.array([[[1],[2],[3]],[[4],[5],[6]],[[2],[9],[121]]])
print(z)

[[[  1]
  [  2]
  [  3]]

 [[  4]
  [  5]
  [  6]]

 [[  2]
  [  9]
  [121]]]


In [23]:
b=np.array(z)
print(b)

[[[  1]
  [  2]
  [  3]]

 [[  4]
  [  5]
  [  6]]

 [[  2]
  [  9]
  [121]]]


In [24]:
b[0]

array([[1],
       [2],
       [3]])

In [25]:
b[0][1]

array([2])

In [26]:
b[0][1][0]

2

In [27]:
b.shape

(3, 3, 1)

In [32]:
a=np.array([[[1],[2],[3]],[[1],[3],[5]]])
print(a)
a.shape

[[[1]
  [2]
  [3]]

 [[1]
  [3]
  [5]]]


(2, 3, 1)

In [33]:
a.size

6

## creating complex array

In [35]:
c=np.array([1,2,3],dtype=complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j]


## array slicing

In [37]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
x[:5]


array([0, 1, 2, 3, 4])

In [44]:
x[::2]

array([0, 2, 4, 6, 8])

In [45]:
x[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x[:6:2]

array([0, 2, 4])

In [47]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[5::-2]

array([5, 3, 1])

## reshaping arrays

In [54]:
s=np.arange(1,10).reshape((3,3))
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## concatenation of arays

In [58]:
x=np.array([1,2])
y=np.array([1,2,3])
np.concatenate([x,y])

array([1, 2, 1, 2, 3])

In [60]:
x[1]+y[0]

3

## spliting of arrays

In [66]:
x=[1,2,3,4,5,6,7,8]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8]


In [68]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [80]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
c=np.zeros((3,3),int)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [85]:
a=1
print(np.sqrt(a))
print(np.sin(30))
print(np.log(a))


1.0
-0.9880316240928618
0.0


In [86]:
x=np.random.rand(2,3)
x

array([[0.13948556, 0.36749347, 0.38086307],
       [0.65094204, 0.34644712, 0.58909361]])

In [87]:
x=np.random.randint(3,size=10)
x

array([0, 2, 1, 1, 1, 2, 2, 0, 0, 1])

In [89]:
x=np.random.randf(3.0,size=10)
x

AttributeError: module 'numpy.random' has no attribute 'randf'

In [91]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [92]:
print(len(dir(np)))

620


In [94]:
print(np.__version__)

1.19.2


## filtering arrays

In [97]:
ary=np.array([11,22,33,44])
x=[True,False,False,True]
nary=ary[x]
nary

array([11, 44])

In [99]:
filter_ary=ary%2==0
new=ary[filter_ary]
print(filter_ary)
print(new)

[False  True False  True]
[22 44]


In [100]:
filter_ary=ary%2!=0
new=ary[filter_ary]
print(filter_ary)
print(new)

[ True False  True False]
[11 33]


In [101]:
y=np.array([[1,2,3],[3,4,5]])
print(np.amax(y,1))

[3 5]
